resource_types:
  - name: npm-cache
    type: docker-image
    source: {repository: ymedlop/npm-cache-resource}

resources:
- name: npm-repo-cache
  type: npm-cache
  source:
    <<: *repo-source
    yarn-support: true

- name: repo
  type: git
  source: &repo-source
    uri: https://github.com/OpenUserCSS/openusercss.org.git
    branch: master

jobs:
- name: cache
  plan:
    - get: repo
      trigger: true
    - get: npm-repo-cache

- name: test
  plan:
  - get: repo
    trigger: true
    passed:
      - cache
  - get: npm-repo-cache
    passed:
      - cache
  - task: test:end-to-end
    file: repo/ci/tasks/test/end-to-end.yml
  - task: test:api
    file: repo/ci/tasks/test/api.yml
  - task: test:unit
    file: repo/ci/tasks/test/unit.yml

- name: build
  plan:
  - get: repo
    trigger: true
    passed:
      - test
  - get: npm-repo-cache
    passed:
      - cache
  - task: build:prod
    file: repo/ci/tasks/build/prod.yml
  - task: build:fast
    file: repo/ci/tasks/build/fast.yml
