resources:
- name: repo
  type: git
  source:
    uri: https://github.com/OpenUserCSS/openusercss.org.git
    branch: master

jobs:
- name: test
  public: true
  plan:
  - get: repo
    trigger: true
  - task: test:end-to-end
    file: repo/ci/tasks/test/end-to-end.yml
  - task: test:api
    file: repo/ci/tasks/test/api.yml
  - task: test:unit
    file: repo/ci/tasks/test/unit.yml

- name: build
  public: true
  plan:
  - get: repo
    trigger: true
    passed:
      - test
  - task: build:prod
    file: repo/ci/tasks/build/prod.yml
  - task: build:fast
    file: repo/ci/tasks/build/fast.yml
