resources:
- name: repo
  type: git
  source:
    uri: https://github.com/OpenUserCSS/openusercss.org.git
    branch: master

jobs:
- name: test
  public: true
  build_logs_to_retain: 100
  plan:
  - get: repo
    trigger: true
  - task: test:ci
    file: repo/ci/tasks/test.yml

- name: approve
  public: true
  build_logs_to_retain: 100
  plan:
  - get: repo
    trigger: true
    passed:
      - test
  - task: approve
    file: repo/ci/tasks/approve.yml
