resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: repo
  type: git
  source:
    uri: https://github.com/OpenUserCSS/openusercss.org.git
    branch: master

- name: pr
  type: pull-request
  source:
    repo: OpenUserCSS/openusercss.org
    access_token: ((githubPersonalToken))
    username: ((githubUsername))
    password: ((githubPassword))

jobs:
- name: test
  public: true
  plan:
  - get: pr
    version: every
    trigger: true
  - put: pr
    params:
      path: pr
      status: pending
      context: test

  - get: repo
  - task: test:ci
    file: repo/ci/tasks/test.yml

  on_failure:
    put: pr
    params:
      path: pr
      status: failure
      context: test
      comment: repo/ci/messages/test-failed.txt

  on_abort:
    put: pr
    params:
      path: pr
      status: failure
      context: test
      comment: repo/ci/messages/aborted.txt

- name: approve
  public: true
  plan:
  - get: pr
    trigger: true
    passed:
      - test
  - put: pr
    params:
      path: pr
      status: pending
      context: approve

  - get: repo
    passed:
      - test
  - task: approve
    file: repo/ci/tasks/approve.yml

  on_success:
    put: pr
    params:
      path: pr
      status: success
      context: approve
      comment: repo/ci/messages/success.txt

  on_failure:
    put: pr
    params:
      path: pr
      status: failure
      context: approve
      comment: repo/ci/messages/approve-failed.txt

  on_abort:
    put: pr
    params:
      path: pr
      status: failure
      context: approve
      comment: repo/ci/messages/aborted.txt
