resource_types:
  - name: npm-cache
    type: docker-image
    source: {repository: ymedlop/npm-cache-resource}

resources:
- name: npm-repo-cache
  type: npm-cache
  source:
    <<: *repo-source
    yarn-support: true
    paths:
      - package.json
      - yarn.lock

- name: repo
  type: git
  source: &repo-source
    uri: https://github.com/OpenUserCSS/openusercss.org.git
    branch: master

jobs:
- name: cache
  plan:
    - get: repo
      trigger: true
    - get: npm-repo-cache

- name: test:unit
  plan:
  - get: repo
    passed:
      - cache
  - get: npm-repo-cache
    trigger: true
    passed: [cache]
  - task: test:unit
    file: repo/ci/tasks/test/unit.yml

- name: test:api
  plan:
  - get: repo
    passed:
      - cache
  - get: npm-repo-cache
    trigger: true
    passed: [cache]
  - task: test:api
    file: repo/ci/tasks/test/api.yml

- name: test:end-to-end
  plan:
  - get: repo
    passed:
      - cache
  - get: npm-repo-cache
    trigger: true
    passed: [cache]
  - task: test:end-to-end
    file: repo/ci/tasks/test/end-to-end.yml
