checkNewVersion = false
defaultEntryPoints = ["http"]
InsecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
  address = "[::]:80"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "dev.openusercss.local"
watch = true
exposedbydefault = false
