---
platform: linux

inputs:
  - name: repo
  - name: pr
    optional: true

caches:
- path: repo/node_modules

image_resource:
  type: docker-image
  source:
    repository: mhart/alpine-node

run:
  path: sh
  args:
    - -exc
    - |
      source repo/ci/scripts/bootstrap.sh
      source repo/ci/scripts/approve.sh
      dependencies python make g++ krb5-dev
      approve_pre
      npm run build:fast
      approve_post

params:
  NODE_ENV: development
  CI: true
