---
platform: linux

inputs:
  - name: repo
  - name: pr
    optional: true

caches:
- path: repo/node_modules
- path: ci/node_modules

image_resource:
  type: docker-image
  source:
    repository: mhart/alpine-node

run:
  path: sh
  args:
    - repo/ci/scripts/tasks/approve.sh

params:
  NODE_ENV: development
  CI: true
