query($limit: Int) {
  popularThemes(limit: $limit) {
    _id
    user {
      _id
      username
      displayname
      avatarUrl
      smallAvatarUrl
    }
    title
    description
    content
    createdAt
    lastUpdate
    version
    screenshots
    license
    variables {
      type
      label
      name
      value
    }
  }
}
