query($terms: String!, $limit: Int, $skip: Int) {
  search(terms: $terms, limit: $limit, skip: $skip) {
    users {
      _id
      username
      displayname
      avatarUrl
      smallAvatarUrl
      lastSeen
    }

    themes {
      _id
      user {
        _id
        username
        displayname
        avatarUrl
        smallAvatarUrl
      }
      title
      createdAt
      lastUpdate
      screenshots
    }
  }
}
